on: 
  #repository_dispatch:
  push:
    branches: [master]
    paths:
      - 'containers/**'

jobs:
  build:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build dotnet
        run: |
          docker build -f ./containers/dotnet/.devcontainer/base.Dockerfile ./containers/dotnet/.devcontainer
      - name: Build angular
        run: |
          docker build -f ./containers/angular/.devcontainer/base.Dockerfile ./containers/angular/.devcontainer
      - name: Build exercism
        run: |
          docker build -f ./containers/exercism/.devcontainer/Dockerfile ./containers/angular/.devcontainer
      - name: Build antlr
        run: |
          docker build -f ./containers/antlr/.devcontainer/Dockerfile ./containers/antlr/.devcontainer
